In [2]:
!pip install boto3

Collecting boto3
  Using cached boto3-1.43.2-py3-none-any.whl (140 kB)
Collecting jmespath<2.0.0,>=0.7.1
  Using cached jmespath-1.1.0-py3-none-any.whl (20 kB)
Collecting s3transfer<0.18.0,>=0.17.0
  Using cached s3transfer-0.17.0-py3-none-any.whl (86 kB)
Collecting botocore<1.44.0,>=1.43.2
  Using cached botocore-1.43.2-py3-none-any.whl (15.0 MB)
Requirement already satisfied: python-dateutil<3.0.0,>=2.1 in c:\users\monaa\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages (from botocore<1.44.0,>=1.43.2->boto3) (2.9.0.post0)
Collecting urllib3!=2.2.0,<3,>=1.25.4
  Downloading urllib3-2.6.3-py3-none-any.whl (131 kB)
     ---------------------------------------- 0.0/131.6 kB ? eta -:--:--
     --- ------------------------------------ 10.2/131.6 kB ? eta -:--:--
     ----- ------------------------------- 20.5/131.6 kB 222.6 kB/s eta 0:00:01
     -------- ---------------------------- 30.7/131.6 kB 220.2 kB/s eta 0:00:01
     ----------- ------------------------- 41.0/131.6 kB 219.4 kB/s eta 0:00:01
     ----------------- ------------------- 61.4/131.6 kB 273.8 kB/s eta 0:00:01
     ----------------- ------------------- 61.4/131.6 kB 273.8 kB/s eta 0:00:01
     -------------------- ---------------- 71.7/131.6 kB 231.8 kB/s eta 0:00:01
     ---------------------------- ------- 102.4/131.6 kB 295.4 kB/s eta 0:00:01
     ------------------------------------ 131.6/131.6 kB 323.6 kB/s eta 0:00:00
Requirement already satisfied: six>=1.5 in c:\users\monaa\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages (from python-dateutil<3.0.0,>=2.1->botocore<1.44.0,>=1.43.2->boto3) (1.17.0)
Installing collected packages: urllib3, jmespath, botocore, s3transfer, boto3
Successfully installed boto3-1.43.2 botocore-1.43.2 jmespath-1.1.0 s3transfer-0.17.0 urllib3-2.6.3

[notice] A new release of pip is available: 23.0.1 -> 26.1
[notice] To update, run: C:\Users\monaa\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip

In [10]:
!pip install requests

Collecting requests
  Downloading requests-2.33.1-py3-none-any.whl (64 kB)
     ---------------------------------------- 0.0/64.9 kB ? eta -:--:--
     ---------------------------------------- 0.0/64.9 kB ? eta -:--:--
     ---------------------------------------- 0.0/64.9 kB ? eta -:--:--
     ---------------------------------------- 0.0/64.9 kB ? eta -:--:--
     ------ --------------------------------- 10.2/64.9 kB ? eta -:--:--
     ------ --------------------------------- 10.2/64.9 kB ? eta -:--:--
     ------ --------------------------------- 10.2/64.9 kB ? eta -:--:--
     ------ --------------------------------- 10.2/64.9 kB ? eta -:--:--
     ------ --------------------------------- 10.2/64.9 kB ? eta -:--:--
     ------ --------------------------------- 10.2/64.9 kB ? eta -:--:--
     ------------------ -------------------- 30.7/64.9 kB 81.9 kB/s eta 0:00:01
     ------------------ -------------------- 30.7/64.9 kB 81.9 kB/s eta 0:00:01
     ------------------------ -------------- 41.0/64.9 kB 89.3 kB/s eta 0:00:01
     -------------------------------------- 64.9/64.9 kB 134.4 kB/s eta 0:00:00
Requirement already satisfied: certifi>=2023.5.7 in c:\users\monaa\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages (from requests) (2026.4.22)
Requirement already satisfied: idna<4,>=2.5 in c:\users\monaa\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages (from requests) (3.13)
Collecting charset_normalizer<4,>=2
  Downloading charset_normalizer-3.4.7-cp310-cp310-win_amd64.whl (159 kB)
     ---------------------------------------- 0.0/159.2 kB ? eta -:--:--
     ---------------------------------------- 0.0/159.2 kB ? eta -:--:--
     ---------------------------------------- 0.0/159.2 kB ? eta -:--:--
     -- ------------------------------------- 10.2/159.2 kB ? eta -:--:--
     -- ------------------------------------- 10.2/159.2 kB ? eta -:--:--
     -- ------------------------------------- 10.2/159.2 kB ? eta -:--:--
     ------- ----------------------------- 30.7/159.2 kB 119.1 kB/s eta 0:00:02
     ------- ----------------------------- 30.7/159.2 kB 119.1 kB/s eta 0:00:02
     --------- --------------------------- 41.0/159.2 kB 122.9 kB/s eta 0:00:01
     -------------- ---------------------- 61.4/159.2 kB 172.4 kB/s eta 0:00:01
     -------------- ---------------------- 61.4/159.2 kB 172.4 kB/s eta 0:00:01
     ---------------- -------------------- 71.7/159.2 kB 157.1 kB/s eta 0:00:01
     ---------------- -------------------- 71.7/159.2 kB 157.1 kB/s eta 0:00:01
     ---------------- -------------------- 71.7/159.2 kB 157.1 kB/s eta 0:00:01
     ---------------- -------------------- 71.7/159.2 kB 157.1 kB/s eta 0:00:01
     ---------------- -------------------- 71.7/159.2 kB 157.1 kB/s eta 0:00:01
     ---------------- -------------------- 71.7/159.2 kB 157.1 kB/s eta 0:00:01
     ---------------- -------------------- 71.7/159.2 kB 157.1 kB/s eta 0:00:01
     ---------------- -------------------- 71.7/159.2 kB 157.1 kB/s eta 0:00:01
     ---------------- -------------------- 71.7/159.2 kB 157.1 kB/s eta 0:00:01
     ---------------- -------------------- 71.7/159.2 kB 157.1 kB/s eta 0:00:01
     ---------------- -------------------- 71.7/159.2 kB 157.1 kB/s eta 0:00:01
     ---------------- -------------------- 71.7/159.2 kB 157.1 kB/s eta 0:00:01
     ---------------- -------------------- 71.7/159.2 kB 157.1 kB/s eta 0:00:01
     -------------------------------- --- 143.4/159.2 kB 133.1 kB/s eta 0:00:01
     ------------------------------------ 159.2/159.2 kB 138.2 kB/s eta 0:00:00
Requirement already satisfied: urllib3<3,>=1.26 in c:\users\monaa\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages (from requests) (2.6.3)
Installing collected packages: charset_normalizer, requests
Successfully installed charset_normalizer-3.4.7 requests-2.33.1

[notice] A new release of pip is available: 23.0.1 -> 26.1
[notice] To update, run: C:\Users\monaa\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip

In [ ]:
import boto3
from credentials import AWS_ACCESS_KEY_ID, AWS_SECRET_ACCESS_KEY, AWS_SESSION_TOKEN

# Authenticate access to AWS S3
s3 = boto3.client(
    's3',
    aws_access_key_id=AWS_ACCESS_KEY_ID,
    aws_secret_access_key= AWS_SECRET_ACCESS_KEY,
    aws_session_token=AWS_SESSION_TOKEN,
    region_name='us-east-1'
)

print(s3.list_buckets())

{'ResponseMetadata': {'RequestId': 'CN8E490SJ8911V0T', 'HostId': 'ai8pNLTUIRL+HtPKjESElFPqWCuQpWExedYN6lN31U/WkyqHD6M6gbWlAb+d4VN5ERyYQrg8MmA=', 'HTTPStatusCode': 200, 'HTTPHeaders': {'x-amz-id-2': 'ai8pNLTUIRL+HtPKjESElFPqWCuQpWExedYN6lN31U/WkyqHD6M6gbWlAb+d4VN5ERyYQrg8MmA=', 'x-amz-request-id': 'CN8E490SJ8911V0T', 'date': 'Mon, 04 May 2026 16:59:57 GMT', 'content-type': 'application/xml', 'transfer-encoding': 'chunked', 'server': 'AmazonS3'}, 'RetryAttempts': 0}, 'Buckets': [{'Name': 'acharya-cui-sokolenko-mwaa', 'CreationDate': datetime.datetime(2026, 2, 24, 19, 9, 1, tzinfo=tzutc()), 'BucketArn': 'arn:aws:s3:::acharya-cui-sokolenko-mwaa'}, {'Name': 'acharya-de300-wi26', 'CreationDate': datetime.datetime(2026, 2, 17, 6, 21, 19, tzinfo=tzutc()), 'BucketArn': 'arn:aws:s3:::acharya-de300-wi26'}, {'Name': 'adams-agrawal-evensen-mwaa', 'CreationDate': datetime.datetime(2025, 6, 7, 20, 58, 20, tzinfo=tzutc()), 'BucketArn': 'arn:aws:s3:::adams-agrawal-evensen-mwaa'}, {'Name': 'ads-de300winter-airflow', 'CreationDate': datetime.datetime(2025, 3, 7, 21, 45, 43, tzinfo=tzutc()), 'BucketArn': 'arn:aws:s3:::ads-de300winter-airflow'}, {'Name': 'airflow-group6', 'CreationDate': datetime.datetime(2023, 5, 31, 4, 31, 17, tzinfo=tzutc()), 'BucketArn': 'arn:aws:s3:::airflow-group6'}, {'Name': 'airflowgroup5', 'CreationDate': datetime.datetime(2023, 6, 1, 2, 29, 23, tzinfo=tzutc()), 'BucketArn': 'arn:aws:s3:::airflowgroup5'}, {'Name': 'amde300', 'CreationDate': datetime.datetime(2025, 3, 6, 22, 30, tzinfo=tzutc()), 'BucketArn': 'arn:aws:s3:::amde300'}, {'Name': 'andrewawsbucket', 'CreationDate': datetime.datetime(2024, 5, 19, 4, 32, 11, tzinfo=tzutc()), 'BucketArn': 'arn:aws:s3:::andrewawsbucket'}, {'Name': 'atmadja-benjamin-dong-mwaa', 'CreationDate': datetime.datetime(2025, 6, 3, 3, 7, 48, tzinfo=tzutc()), 'BucketArn': 'arn:aws:s3:::atmadja-benjamin-dong-mwaa'}, {'Name': 'atmadja-benson-mcgillis-wu-bucket', 'CreationDate': datetime.datetime(2025, 5, 27, 22, 13, 40, tzinfo=tzutc()), 'BucketArn': 'arn:aws:s3:::atmadja-benson-mcgillis-wu-bucket'}, {'Name': 'aws-logs-549787090008-us-east-1', 'CreationDate': datetime.datetime(2024, 5, 21, 4, 0, 3, tzinfo=tzutc()), 'BucketArn': 'arn:aws:s3:::aws-logs-549787090008-us-east-1'}, {'Name': 'aws-logs-549787090008-us-east-2', 'CreationDate': datetime.datetime(2024, 5, 19, 23, 12, 41, tzinfo=tzutc()), 'BucketArn': 'arn:aws:s3:::aws-logs-549787090008-us-east-2'}, {'Name': 'aws-sam-cli-managed-default-samclisourcebucket-fmrcacmtwnqj', 'CreationDate': datetime.datetime(2023, 12, 11, 21, 3, 23, tzinfo=tzutc()), 'BucketArn': 'arn:aws:s3:::aws-sam-cli-managed-default-samclisourcebucket-fmrcacmtwnqj'}, {'Name': 'aws-sam-cli-managed-default-samclisourcebucket-gkgousezsx38', 'CreationDate': datetime.datetime(2023, 12, 11, 21, 8, 5, tzinfo=tzutc()), 'BucketArn': 'arn:aws:s3:::aws-sam-cli-managed-default-samclisourcebucket-gkgousezsx38'}, {'Name': 'aws-sam-cli-managed-default-samclisourcebucket-jasccrluxmti', 'CreationDate': datetime.datetime(2023, 12, 11, 21, 12, 49, tzinfo=tzutc()), 'BucketArn': 'arn:aws:s3:::aws-sam-cli-managed-default-samclisourcebucket-jasccrluxmti'}, {'Name': 'aws-sam-cli-managed-default-samclisourcebucket-u1dyc2xcx9dr', 'CreationDate': datetime.datetime(2023, 12, 11, 21, 10, 25, tzinfo=tzutc()), 'BucketArn': 'arn:aws:s3:::aws-sam-cli-managed-default-samclisourcebucket-u1dyc2xcx9dr'}, {'Name': 'barnett-evan-lab3', 'CreationDate': datetime.datetime(2026, 4, 30, 21, 18, 9, tzinfo=tzutc()), 'BucketArn': 'arn:aws:s3:::barnett-evan-lab3'}, {'Name': 'beam-gutstein-bucket', 'CreationDate': datetime.datetime(2025, 5, 29, 16, 12, 52, tzinfo=tzutc()), 'BucketArn': 'arn:aws:s3:::beam-gutstein-bucket'}, {'Name': 'benjamin-bucket-lab8', 'CreationDate': datetime.datetime(2025, 5, 27, 23, 29, 5, tzinfo=tzutc()), 'BucketArn': 'arn:aws:s3:::benjamin-bucket-lab8'}, {'Name': 'benson-gillespie-liu-mwaa', 'CreationDate': datetime.datetime(2025, 6, 4, 17, 17, 36, tzinfo=tzutc()), 'BucketArn': 'arn:aws:s3:::benson-gillespie-liu-mwaa'}, {'Name': 'bhh-26spring', 'CreationDate': datetime.datetime(2026, 4, 21, 21, 16, 38, tzinfo=tzutc()), 'BucketArn': 'arn:aws:s3:::bhh-26spring'}, {'Name': 'brennanbensonawsbucket', 'CreationDate': datetime.datetime(2024, 5, 21, 3, 42, 11, tzinfo=tzutc()), 'BucketArn': 'arn:aws:s3:::brennanbensonawsbucket'}, {'Name': 'bustrust', 'CreationDate': datetime.datetime(2026, 2, 12, 18, 2, 15, tzinfo=tzutc()), 'BucketArn': 'arn:aws:s3:::bustrust'}, {'Name': 'carl-w-spring2026', 'CreationDate': datetime.datetime(2026, 4, 21, 21, 16, 36, tzinfo=tzutc()), 'BucketArn': 'arn:aws:s3:::carl-w-spring2026'}, {'Name': 'chen-gutstein-tenesaca-swarup-bucket', 'CreationDate': datetime.datetime(2025, 6, 2, 19, 26, 53, tzinfo=tzutc()), 'BucketArn': 'arn:aws:s3:::chen-gutstein-tenesaca-swarup-bucket'}, {'Name': 'chen-thampeera-wong-kim-swarup-bucket', 'CreationDate': datetime.datetime(2025, 5, 27, 22, 12, 45, tzinfo=tzutc()), 'BucketArn': 'arn:aws:s3:::chen-thampeera-wong-kim-swarup-bucket'}, {'Name': 'data-eng300-hw2-visuthikosol', 'CreationDate': datetime.datetime(2026, 5, 2, 22, 41, tzinfo=tzutc()), 'BucketArn': 'arn:aws:s3:::data-eng300-hw2-visuthikosol'}, {'Name': 'dde300-east1', 'CreationDate': datetime.datetime(2026, 2, 12, 0, 7, 2, tzinfo=tzutc()), 'BucketArn': 'arn:aws:s3:::dde300-east1'}, {'Name': 'de300-1-mwaa', 'CreationDate': datetime.datetime(2023, 6, 1, 20, 51, 51, tzinfo=tzutc()), 'BucketArn': 'arn:aws:s3:::de300-1-mwaa'}, {'Name': 'de300-aimeechooi-airflow', 'CreationDate': datetime.datetime(2024, 3, 5, 19, 13, 21, tzinfo=tzutc()), 'BucketArn': 'arn:aws:s3:::de300-aimeechooi-airflow'}, {'Name': 'de300-airflow-cindy', 'CreationDate': datetime.datetime(2024, 6, 1, 20, 17, 20, tzinfo=tzutc()), 'BucketArn': 'arn:aws:s3:::de300-airflow-cindy'}, {'Name': 'de300-airflow-output', 'CreationDate': datetime.datetime(2023, 6, 7, 17, 8, 56, tzinfo=tzutc()), 'BucketArn': 'arn:aws:s3:::de300-airflow-output'}, {'Name': 'de300-airflow-rachel', 'CreationDate': datetime.datetime(2024, 5, 30, 1, 55, 45, tzinfo=tzutc()), 'BucketArn': 'arn:aws:s3:::de300-airflow-rachel'}, {'Name': 'de300-airflow-tests', 'CreationDate': datetime.datetime(2023, 6, 7, 13, 39, 11, tzinfo=tzutc()), 'BucketArn': 'arn:aws:s3:::de300-airflow-tests'}, {'Name': 'de300-amandakosmen-airflow', 'CreationDate': datetime.datetime(2024, 3, 5, 19, 13, 43, tzinfo=tzutc()), 'BucketArn': 'arn:aws:s3:::de300-amandakosmen-airflow'}, {'Name': 'de300-aws-tutorial', 'CreationDate': datetime.datetime(2023, 5, 20, 1, 0, tzinfo=tzutc()), 'BucketArn': 'arn:aws:s3:::de300-aws-tutorial'}, {'Name': 'de300-benwrather-airflow2', 'CreationDate': datetime.datetime(2024, 3, 5, 19, 18, 38, tzinfo=tzutc()), 'BucketArn': 'arn:aws:s3:::de300-benwrather-airflow2'}, {'Name': 'de300-bzl-wi2026', 'CreationDate': datetime.datetime(2026, 2, 3, 23, 6, 3, tzinfo=tzutc()), 'BucketArn': 'arn:aws:s3:::de300-bzl-wi2026'}, {'Name': 'de300-demo-bucket', 'CreationDate': datetime.datetime(2026, 2, 17, 3, 40, 14, tzinfo=tzutc()), 'BucketArn': 'arn:aws:s3:::de300-demo-bucket'}, {'Name': 'de300-garrettlee-airflow', 'CreationDate': datetime.datetime(2024, 3, 5, 19, 13, tzinfo=tzutc()), 'BucketArn': 'arn:aws:s3:::de300-garrettlee-airflow'}, {'Name': 'de300-group', 'CreationDate': datetime.datetime(2023, 5, 24, 17, 39, 23, tzinfo=tzutc()), 'BucketArn': 'arn:aws:s3:::de300-group'}, {'Name': 'de300-group-17-heartdata', 'CreationDate': datetime.datetime(2023, 5, 31, 23, 30, 47, tzinfo=tzutc()), 'BucketArn': 'arn:aws:s3:::de300-group-17-heartdata'}, {'Name': 'de300-group-17-mwaa', 'CreationDate': datetime.datetime(2023, 5, 30, 21, 9, 41, tzinfo=tzutc()), 'BucketArn': 'arn:aws:s3:::de300-group-17-mwaa'}, {'Name': 'de300-group1', 'CreationDate': datetime.datetime(2023, 5, 22, 17, 21, 17, tzinfo=tzutc()), 'BucketArn': 'arn:aws:s3:::de300-group1'}, {'Name': 'de300-group1-mwaa-output', 'CreationDate': datetime.datetime(2023, 6, 1, 21, 37, 22, tzinfo=tzutc()), 'BucketArn': 'arn:aws:s3:::de300-group1-mwaa-output'}, {'Name': 'de300-group11-mwaa', 'CreationDate': datetime.datetime(2023, 5, 24, 20, 9, 31, tzinfo=tzutc()), 'BucketArn': 'arn:aws:s3:::de300-group11-mwaa'}, {'Name': 'de300-group11-mwaa-output', 'CreationDate': datetime.datetime(2023, 5, 24, 20, 26, 12, tzinfo=tzutc()), 'BucketArn': 'arn:aws:s3:::de300-group11-mwaa-output'}, {'Name': 'de300-group13-airflow', 'CreationDate': datetime.datetime(2023, 5, 25, 15, 33, 25, tzinfo=tzutc()), 'BucketArn': 'arn:aws:s3:::de300-group13-airflow'}, {'Name': 'de300-group13-airflow-output', 'CreationDate': datetime.datetime(2023, 5, 28, 15, 53, 38, tzinfo=tzutc()), 'BucketArn': 'arn:aws:s3:::de300-group13-airflow-output'}, {'Name': 'de300-group2', 'CreationDate': datetime.datetime(2023, 5, 22, 6, 52, 46, tzinfo=tzutc()), 'BucketArn': 'arn:aws:s3:::de300-group2'}, {'Name': 'de300-group7-airflow-output', 'CreationDate': datetime.datetime(2023, 6, 2, 17, 28, 3, tzinfo=tzutc()), 'BucketArn': 'arn:aws:s3:::de300-group7-airflow-output'}, {'Name': 'de300-group7-module3', 'CreationDate': datetime.datetime(2023, 6, 2, 16, 50, 40, tzinfo=tzutc()), 'BucketArn': 'arn:aws:s3:::de300-group7-module3'}, {'Name': 'de300-group7-mwaa', 'CreationDate': datetime.datetime(2023, 6, 2, 7, 16, 34, tzinfo=tzutc()), 'BucketArn': 'arn:aws:s3:::de300-group7-mwaa'}, {'Name': 'de300-group8-airflow-output', 'CreationDate': datetime.datetime(2023, 6, 1, 0, 9, 47, tzinfo=tzutc()), 'BucketArn': 'arn:aws:s3:::de300-group8-airflow-output'}, {'Name': 'de300-group8-mwaa', 'CreationDate': datetime.datetime(2023, 5, 24, 19, 58, 8, tzinfo=tzutc()), 'BucketArn': 'arn:aws:s3:::de300-group8-mwaa'}, {'Name': 'de300-group8-project2', 'CreationDate': datetime.datetime(2023, 5, 22, 15, 0, 38, tzinfo=tzutc()), 'BucketArn': 'arn:aws:s3:::de300-group8-project2'}, {'Name': 'de300-heart-disease-test', 'CreationDate': datetime.datetime(2023, 5, 16, 19, 26, 43, tzinfo=tzutc()), 'BucketArn': 'arn:aws:s3:::de300-heart-disease-test'}, {'Name': 'de300-isaacwinoto-airflow', 'CreationDate': datetime.datetime(2024, 3, 5, 19, 13, 42, tzinfo=tzutc()), 'BucketArn': 'arn:aws:s3:::de300-isaacwinoto-airflow'}, {'Name': 'de300-jasonlu-airflow', 'CreationDate': datetime.datetime(2024, 3, 5, 19, 13, 12, tzinfo=tzutc()), 'BucketArn': 'arn:aws:s3:::de300-jasonlu-airflow'}, {'Name': 'de300-ktv-mwaa', 'CreationDate': datetime.datetime(2026, 2, 17, 19, 8, 48, tzinfo=tzutc()), 'BucketArn': 'arn:aws:s3:::de300-ktv-mwaa'}, {'Name': 'de300-lily-bucket', 'CreationDate': datetime.datetime(2024, 5, 14, 22, 10, 5, tzinfo=tzutc()), 'BucketArn': 'arn:aws:s3:::de300-lily-bucket'}, {'Name': 'de300-marcobenavides-airflow', 'CreationDate': datetime.datetime(2024, 3, 5, 19, 15, 41, tzinfo=tzutc()), 'BucketArn': 'arn:aws:s3:::de300-marcobenavides-airflow'}, {'Name': 'de300-markzhang-airflow', 'CreationDate': datetime.datetime(2024, 3, 5, 19, 14, 5, tzinfo=tzutc()), 'BucketArn': 'arn:aws:s3:::de300-markzhang-airflow'}, {'Name': 'de300-mikang-airflow', 'CreationDate': datetime.datetime(2024, 3, 5, 19, 13, 7, tzinfo=tzutc()), 'BucketArn': 'arn:aws:s3:::de300-mikang-airflow'}, {'Name': 'de300-mwaa', 'CreationDate': datetime.datetime(2023, 5, 20, 14, 29, 35, tzinfo=tzutc()), 'BucketArn': 'arn:aws:s3:::de300-mwaa'}, {'Name': 'de300-mwaa-19', 'CreationDate': datetime.datetime(2023, 5, 30, 16, 16, 24, tzinfo=tzutc()), 'BucketArn': 'arn:aws:s3:::de300-mwaa-19'}, {'Name': 'de300-mwaa-cal', 'CreationDate': datetime.datetime(2025, 3, 6, 4, 52, 58, tzinfo=tzutc()), 'BucketArn': 'arn:aws:s3:::de300-mwaa-cal'}, {'Name': 'de300-mwaa-ohmies', 'CreationDate': datetime.datetime(2026, 2, 17, 19, 8, 36, tzinfo=tzutc()), 'BucketArn': 'arn:aws:s3:::de300-mwaa-ohmies'}, {'Name': 'de300-mwaa-oregon', 'CreationDate': datetime.datetime(2025, 3, 2, 0, 7, 19, tzinfo=tzutc()), 'BucketArn': 'arn:aws:s3:::de300-mwaa-oregon'}, {'Name': 'de300-mwaa-output', 'CreationDate': datetime.datetime(2023, 5, 20, 6, 10, 3, tzinfo=tzutc()), 'BucketArn': 'arn:aws:s3:::de300-mwaa-output'}, {'Name': 'de300-nataliehill-airflow', 'CreationDate': datetime.datetime(2024, 3, 5, 19, 13, 14, tzinfo=tzutc()), 'BucketArn': 'arn:aws:s3:::de300-nataliehill-airflow'}, {'Name': 'de300-p3-g2', 'CreationDate': datetime.datetime(2023, 5, 27, 16, 53, 33, tzinfo=tzutc()), 'BucketArn': 'arn:aws:s3:::de300-p3-g2'}, {'Name': 'de300-phoebekim-airflow', 'CreationDate': datetime.datetime(2024, 3, 5, 19, 13, 13, tzinfo=tzutc()), 'BucketArn': 'arn:aws:s3:::de300-phoebekim-airflow'}, {'Name': 'de300-project-19', 'CreationDate': datetime.datetime(2023, 5, 22, 1, 3, 44, tzinfo=tzutc()), 'BucketArn': 'arn:aws:s3:::de300-project-19'}, {'Name': 'de300-project-group17', 'CreationDate': datetime.datetime(2023, 5, 21, 22, 59, 36, tzinfo=tzutc()), 'BucketArn': 'arn:aws:s3:::de300-project-group17'}, {'Name': 'de300-project3-group20', 'CreationDate': datetime.datetime(2023, 5, 30, 0, 59, 1, tzinfo=tzutc()), 'BucketArn': 'arn:aws:s3:::de300-project3-group20'}, {'Name': 'de300-project3-group20-output', 'CreationDate': datetime.datetime(2023, 5, 30, 1, 58, 17, tzinfo=tzutc()), 'BucketArn': 'arn:aws:s3:::de300-project3-group20-output'}, {'Name': 'de300-project4', 'CreationDate': datetime.datetime(2023, 5, 22, 3, 38, 41, tzinfo=tzutc()), 'BucketArn': 'arn:aws:s3:::de300-project4'}, {'Name': 'de300-project4-mwaa', 'CreationDate': datetime.datetime(2023, 6, 4, 13, 50, 55, tzinfo=tzutc()), 'BucketArn': 'arn:aws:s3:::de300-project4-mwaa'}, {'Name': 'de300-project4-mwaa-output', 'CreationDate': datetime.datetime(2023, 6, 6, 15, 49, 4, tzinfo=tzutc()), 'BucketArn': 'arn:aws:s3:::de300-project4-mwaa-output'}, {'Name': 'de300-riadsouza-airflow', 'CreationDate': datetime.datetime(2024, 3, 5, 19, 13, 30, tzinfo=tzutc()), 'BucketArn': 'arn:aws:s3:::de300-riadsouza-airflow'}, {'Name': 'de300-rodneyreichert-airflow', 'CreationDate': datetime.datetime(2024, 3, 5, 19, 13, 17, tzinfo=tzutc()), 'BucketArn': 'arn:aws:s3:::de300-rodneyreichert-airflow'}, {'Name': 'de300-sebphemister-airflow', 'CreationDate': datetime.datetime(2024, 3, 5, 19, 13, 48, tzinfo=tzutc()), 'BucketArn': 'arn:aws:s3:::de300-sebphemister-airflow'}, {'Name': 'de300-shreyasridhar-airflow', 'CreationDate': datetime.datetime(2024, 3, 5, 19, 13, 21, tzinfo=tzutc()), 'BucketArn': 'arn:aws:s3:::de300-shreyasridhar-airflow'}, {'Name': 'de300-wakiuruwachiuri-airflow', 'CreationDate': datetime.datetime(2024, 3, 5, 19, 13, 51, tzinfo=tzutc()), 'BucketArn': 'arn:aws:s3:::de300-wakiuruwachiuri-airflow'}, {'Name': 'de300-wilks', 'CreationDate': datetime.datetime(2026, 2, 15, 16, 11, 21, tzinfo=tzutc()), 'BucketArn': 'arn:aws:s3:::de300-wilks'}, {'Name': 'de300-wn2024', 'CreationDate': datetime.datetime(2024, 2, 7, 18, 46, 29, tzinfo=tzutc()), 'BucketArn': 'arn:aws:s3:::de300-wn2024'}, {'Name': 'de300-wn2024-airflow', 'CreationDate': datetime.datetime(2024, 3, 5, 3, 6, 42, tzinfo=tzutc()), 'BucketArn': 'arn:aws:s3:::de300-wn2024-airflow'}, {'Name': 'de300-ziadelbadry', 'CreationDate': datetime.datetime(2024, 6, 7, 22, 5, 35, tzinfo=tzutc()), 'BucketArn': 'arn:aws:s3:::de300-ziadelbadry'}, {'Name': 'de300group13', 'CreationDate': datetime.datetime(2023, 5, 22, 2, 23, 58, tzinfo=tzutc()), 'BucketArn': 'arn:aws:s3:::de300group13'}, {'Name': 'de300spring2025', 'CreationDate': datetime.datetime(2025, 4, 15, 20, 12, 25, tzinfo=tzutc()), 'BucketArn': 'arn:aws:s3:::de300spring2025'}, {'Name': 'de300winter-airflow', 'CreationDate': datetime.datetime(2025, 3, 4, 3, 49, 41, tzinfo=tzutc()), 'BucketArn': 'arn:aws:s3:::de300winter-airflow'}, {'Name': 'de300winter2025', 'CreationDate': datetime.datetime(2025, 1, 21, 4, 32, 26, tzinfo=tzutc()), 'BucketArn': 'arn:aws:s3:::de300winter2025'}, {'Name': 'decherrie-winter26', 'CreationDate': datetime.datetime(2026, 2, 3, 23, 6, 4, tzinfo=tzutc()), 'BucketArn': 'arn:aws:s3:::decherrie-winter26'}, {'Name': 'desmond-hw4-airflow', 'CreationDate': datetime.datetime(2025, 3, 10, 18, 45, 30, tzinfo=tzutc()), 'BucketArn': 'arn:aws:s3:::desmond-hw4-airflow'}, {'Name': 'desmond-mwaa-lab8', 'CreationDate': datetime.datetime(2025, 3, 9, 21, 34, 54, tzinfo=tzutc()), 'BucketArn': 'arn:aws:s3:::desmond-mwaa-lab8'}, {'Name': 'desmondlab8', 'CreationDate': datetime.datetime(2025, 3, 9, 19, 50, 43, tzinfo=tzutc()), 'BucketArn': 'arn:aws:s3:::desmondlab8'}, {'Name': 'desmondnebahspark', 'CreationDate': datetime.datetime(2025, 2, 25, 1, 46, 30, tzinfo=tzutc()), 'BucketArn': 'arn:aws:s3:::desmondnebahspark'}, {'Name': 'dinglin-spring26', 'CreationDate': datetime.datetime(2026, 4, 28, 16, 23, 13, tzinfo=tzutc()), 'BucketArn': 'arn:aws:s3:::dinglin-spring26'}, {'Name': 'dinglin-winter26', 'CreationDate': datetime.datetime(2026, 2, 3, 3, 37, 9, tzinfo=tzutc()), 'BucketArn': 'arn:aws:s3:::dinglin-winter26'}, {'Name': 'don-bucket-lab8', 'CreationDate': datetime.datetime(2025, 3, 10, 15, 11, 3, tzinfo=tzutc()), 'BucketArn': 'arn:aws:s3:::don-bucket-lab8'}, {'Name': 'dongjdu8459-bucket', 'CreationDate': datetime.datetime(2025, 5, 27, 22, 43, 24, tzinfo=tzutc()), 'BucketArn': 'arn:aws:s3:::dongjdu8459-bucket'}, {'Name': 'dongjoo-26spring', 'CreationDate': datetime.datetime(2026, 4, 21, 21, 16, 44, tzinfo=tzutc()), 'BucketArn': 'arn:aws:s3:::dongjoo-26spring'}, {'Name': 'dse300-rheashah-airflow', 'CreationDate': datetime.datetime(2024, 3, 5, 19, 17, 2, tzinfo=tzutc()), 'BucketArn': 'arn:aws:s3:::dse300-rheashah-airflow'}, {'Name': 'dxk-mwaa', 'CreationDate': datetime.datetime(2025, 2, 25, 5, 49, 15, tzinfo=tzutc()), 'BucketArn': 'arn:aws:s3:::dxk-mwaa'}, {'Name': 'elasticbeanstalk-us-east-2-549787090008', 'CreationDate': datetime.datetime(2023, 5, 12, 20, 12, 24, tzinfo=tzutc()), 'BucketArn': 'arn:aws:s3:::elasticbeanstalk-us-east-2-549787090008'}, {'Name': 'eo-airflow-group16', 'CreationDate': datetime.datetime(2023, 6, 2, 1, 8, 10, tzinfo=tzutc()), 'BucketArn': 'arn:aws:s3:::eo-airflow-group16'}, {'Name': 'eobucket-group16', 'CreationDate': datetime.datetime(2023, 5, 19, 4, 25, 17, tzinfo=tzutc()), 'BucketArn': 'arn:aws:s3:::eobucket-group16'}, {'Name': 'evensen-bucket', 'CreationDate': datetime.datetime(2025, 6, 4, 18, 37, 42, tzinfo=tzutc()), 'BucketArn': 'arn:aws:s3:::evensen-bucket'}, {'Name': 'fingerson-lacombefarina-mwaa', 'CreationDate': datetime.datetime(2026, 2, 24, 20, 32, 37, tzinfo=tzutc()), 'BucketArn': 'arn:aws:s3:::fingerson-lacombefarina-mwaa'}, {'Name': 'fingerson-winter26', 'CreationDate': datetime.datetime(2026, 2, 4, 0, 9, 32, tzinfo=tzutc()), 'BucketArn': 'arn:aws:s3:::fingerson-winter26'}, {'Name': 'gillespie-tenesaca-adams', 'CreationDate': datetime.datetime(2025, 5, 27, 22, 23, 20, tzinfo=tzutc()), 'BucketArn': 'arn:aws:s3:::gillespie-tenesaca-adams'}, {'Name': 'gomaa-hw2', 'CreationDate': datetime.datetime(2026, 5, 4, 16, 40, 45, tzinfo=tzutc()), 'BucketArn': 'arn:aws:s3:::gomaa-hw2'}, {'Name': 'group10-airflow', 'CreationDate': datetime.datetime(2023, 5, 30, 21, 24, 20, tzinfo=tzutc()), 'BucketArn': 'arn:aws:s3:::group10-airflow'}, {'Name': 'group11-data', 'CreationDate': datetime.datetime(2023, 5, 21, 18, 27, 45, tzinfo=tzutc()), 'BucketArn': 'arn:aws:s3:::group11-data'}, {'Name': 'group14-mwaa', 'CreationDate': datetime.datetime(2023, 5, 30, 3, 14, 32, tzinfo=tzutc()), 'BucketArn': 'arn:aws:s3:::group14-mwaa'}, {'Name': 'group14-project3', 'CreationDate': datetime.datetime(2023, 5, 30, 16, 2, 53, tzinfo=tzutc()), 'BucketArn': 'arn:aws:s3:::group14-project3'}, {'Name': 'group14-wine', 'CreationDate': datetime.datetime(2023, 5, 31, 4, 43, 1, tzinfo=tzutc()), 'BucketArn': 'arn:aws:s3:::group14-wine'}, {'Name': 'group15-de300', 'CreationDate': datetime.datetime(2023, 5, 19, 16, 16, 16, tzinfo=tzutc()), 'BucketArn': 'arn:aws:s3:::group15-de300'}, {'Name': 'group15-module3', 'CreationDate': datetime.datetime(2023, 5, 28, 18, 14, 58, tzinfo=tzutc()), 'BucketArn': 'arn:aws:s3:::group15-module3'}, {'Name': 'group19-mwaa-output', 'CreationDate': datetime.datetime(2023, 5, 31, 16, 32, 28, tzinfo=tzutc()), 'BucketArn': 'arn:aws:s3:::group19-mwaa-output'}, {'Name': 'group20-de300', 'CreationDate': datetime.datetime(2023, 5, 22, 1, 50, 21, tzinfo=tzutc()), 'BucketArn': 'arn

In [ ]:
import boto3
import requests

# Download the movielens dataset zip, and skips it's already in S3
def download_upload_dataset(bucket_name, s3_key="data/ml-1m.zip"):
    
    try:
        s3.head_object(Bucket=bucket_name, Key=s3_key)
        print(f"Dataset already exists in s3://{bucket_name}/{s3_key}. No need to download.")
        return
    except:
        print("Downloading dataset...")
    
    url = "https://files.grouplens.org/datasets/movielens/ml-1m.zip"
    response = requests.get(url)
    
    s3.put_object(Bucket=bucket_name, Key=s3_key, Body=response.content)
    print(f"Uploaded to s3://{bucket_name}/{s3_key}")

download_upload_dataset("gomaa-hw2")

Downloading dataset...
Uploaded to s3://gomaa-hw2/data/ml-1m.zip

In [ ]:
# Confirm dataset was uploaded to S3
response = s3.list_objects_v2(Bucket="gomaa-hw2")
for obj in response.get("Contents", []):
    print(obj["Key"])

data/ml-1m.zip

In [ ]:
import zipfile
import io
import pandas as pd

# Load movies released pre or in 1980
def load_movies(s3, bucket_name, s3_key="data/ml-1m.zip"):
    obj = s3.get_object(Bucket=bucket_name, Key=s3_key)
    zip_bytes = io.BytesIO(obj["Body"].read())
    
    with zipfile.ZipFile(zip_bytes) as z:
        with z.open("ml-1m/movies.dat") as f:
            movies = pd.read_csv(f, sep="::", engine="python", 
                                 names=["MovieID", "Title", "Genres"], 
                                 encoding="latin-1")
    
    movies["Year"] = movies["Title"].str.extract(r'\((\d{4})\)').astype(int)
    movies_pre1980 = movies[movies["Year"] <= 1980]
    
    return movies_pre1980

movies_pre1980 = load_movies(s3, "gomaa-hw2")
print(f"Movies released on/before 1980: {len(movies_pre1980)}")
movies_pre1980.head()

Movies released on/before 1980: 887

,MovieID,Title,Genres,Year
109,111,Taxi Driver (1976),Drama|Thriller,1976
152,154,Belle de jour (1967),Drama,1967
197,199,"Umbrellas of Cherbourg, The (Parapluies de Che...",Drama|Musical,1964
257,260,Star Wars: Episode IV - A New Hope (1977),Action|Adventure|Fantasy|Sci-Fi,1977
386,390,Faster Pussycat! Kill! Kill! (1965),Action|Comedy|Drama,1965

In [ ]:
import numpy as np
from sentence_transformers import SentenceTransformer

# Creates new BERT embeddings and saves to S3 (skips if already there)
def create_embeddings(movies_df, s3, bucket_name, s3_key="embeddings/pre1980_embeddings.npy"):
    try:
        s3.head_object(Bucket=bucket_name, Key=s3_key)
        print("Embeddings already exist in S3. Loading...")
        obj = s3.get_object(Bucket=bucket_name, Key=s3_key)
        embeddings = np.load(io.BytesIO(obj["Body"].read()))
        return embeddings
    except:
        print("Creating embeddings...")

    movies_df["text"] = movies_df["Title"] + ": " + movies_df["Genres"].str.replace("|", " ", regex=False)
    
    model = SentenceTransformer("all-MiniLM-L6-v2")
    embeddings = model.encode(movies_df["text"].tolist(), show_progress_bar=True)
    
    buffer = io.BytesIO()
    np.save(buffer, embeddings)
    buffer.seek(0)
    s3.put_object(Bucket=bucket_name, Key=s3_key, Body=buffer.read())
    print(f"Embeddings saved to s3://{bucket_name}/{s3_key}")
    
    return embeddings

embeddings_pre1980 = create_embeddings(movies_pre1980, s3, "gomaa-hw2")
print(f"Embeddings shape: {embeddings_pre1980.shape}")

C:\Users\monaa\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

Creating embeddings...

C:\Users\monaa\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\huggingface_hub\file_download.py:138: UserWarning: `huggingface_hub` cache-system uses symlinks by default to efficiently store duplicated files but your machine does not support them in C:\Users\monaa\.cache\huggingface\hub\models--sentence-transformers--all-MiniLM-L6-v2. Caching files will still work but in a degraded version that might require more space on your disk. This warning can be disabled by setting the `HF_HUB_DISABLE_SYMLINKS_WARNING` environment variable. For more details, see https://huggingface.co/docs/huggingface_hub/how-to-cache#limitations.
To support symlinks on Windows, you either need to activate Developer Mode or to run Python as an administrator. In order to activate developer mode, see this article: https://docs.microsoft.com/en-us/windows/apps/get-started/enable-your-device-for-development
  warnings.warn(message)
Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
Loading weights: 100%|██████████| 103/103 [00:00<00:00, 8583.78it/s]
Batches: 100%|██████████| 28/28 [00:01<00:00, 24.49it/s]

Embeddings saved to s3://gomaa-hw2/embeddings/pre1980_embeddings.npy
Embeddings shape: (887, 384)

In [17]:
def load_ratings_from_s3(s3, bucket_name, s3_key="data/ml-1m.zip"):
    obj = s3.get_object(Bucket=bucket_name, Key=s3_key)
    zip_bytes = io.BytesIO(obj["Body"].read())
    
    with zipfile.ZipFile(zip_bytes) as z:
        with z.open("ml-1m/ratings.dat") as f:
            ratings = pd.read_csv(f, sep="::", engine="python",
                                  names=["UserID", "MovieID", "Rating", "Timestamp"],
                                  encoding="latin-1")
    return ratings

ratings = load_ratings_from_s3(s3, "gomaa-hw2")
ratings.head()

   UserID  MovieID  Rating  Timestamp
0       1     1193       5  978300760
1       1      661       3  978302109
2       1      914       3  978301968
3       1     3408       4  978300275
4       1     2355       5  978824291

In [ ]:
from sklearn.metrics.pairwise import cosine_similarity

# Finds random top user
def get_top_user(ratings):
    user_counts = ratings.groupby("UserID").size()
    threshold = user_counts.quantile(0.95)
    top_users = user_counts[user_counts >= threshold].index
    return np.random.choice(top_users)

# Recommends 5 movies for top/cold user and saves to S3
def recommend_movies(user_type, movies_df, embeddings, ratings, s3, bucket_name, top_user_id=None):
    if user_type == "cold":
        popular = ratings.groupby("MovieID").size().reset_index(name="count")
        popular = popular[popular["MovieID"].isin(movies_df["MovieID"])]
        top5 = popular.sort_values("count", ascending=False).head(5)
        recommendations = movies_df[movies_df["MovieID"].isin(top5["MovieID"])][["MovieID", "Title"]]
        user_summary = {"User_Type": "cold", "Last_Interaction_Time": None, "Num_Ratings": 0}

    elif user_type == "top":
        user_ratings = ratings[ratings["UserID"] == top_user_id]
        liked = user_ratings[user_ratings["Rating"] >= 4]["MovieID"]
        liked_indices = movies_df[movies_df["MovieID"].isin(liked)].index
        movies_df_reset = movies_df.reset_index(drop=True)
        liked_indices = movies_df_reset[movies_df_reset["MovieID"].isin(liked)].index
        
        if len(liked_indices) == 0:
            taste_vector = embeddings.mean(axis=0, keepdims=True)
        else:
            taste_vector = embeddings[liked_indices].mean(axis=0, keepdims=True)
        
        sims = cosine_similarity(taste_vector, embeddings)[0]
        top_indices = sims.argsort()[::-1][:5]
        recommendations = movies_df_reset.iloc[top_indices][["MovieID", "Title"]]
        
        last_time = pd.to_datetime(user_ratings["Timestamp"].max(), unit="s")
        user_summary = {"User_Type": "top", "Last_Interaction_Time": str(last_time), 
                        "Num_Ratings": len(user_ratings)}

    result = {**user_summary, "Recommendations": recommendations["Title"].tolist()}
    
    buffer = io.BytesIO(pd.DataFrame([result]).to_json().encode())
    s3.put_object(Bucket=bucket_name, Key=f"recommendations/{user_type}_user.json", Body=buffer.read())
    print(f"Saved to S3: recommendations/{user_type}_user.json")
    
    return result

top_user_id = get_top_user(ratings)
cold_result = recommend_movies("cold", movies_pre1980, embeddings_pre1980, ratings, s3, "gomaa-hw2")
top_result = recommend_movies("top", movies_pre1980, embeddings_pre1980, ratings, s3, "gomaa-hw2", top_user_id)

print(cold_result)
print(top_result)

Saved to S3: recommendations/cold_user.json
Saved to S3: recommendations/top_user.json
{'User_Type': 'cold', 'Last_Interaction_Time': None, 'Num_Ratings': 0, 'Recommendations': ['Star Wars: Episode IV - A New Hope (1977)', 'Godfather, The (1972)', 'Star Wars: Episode V - The Empire Strikes Back (1980)', 'Alien (1979)', 'Airplane! (1980)']}
{'User_Type': 'top', 'Last_Interaction_Time': '2001-02-15 18:18:13', 'Num_Ratings': 649, 'Recommendations': ['Very Natural Thing, A (1974)', 'Windows (1980)', 'Close Encounters of the Third Kind (1977)', 'Mad Max (1979)', 'Apocalypse Now (1979)']}

In [ ]:
# Loads full movie set to S3 without redundancy
def load_all_movies(s3, bucket_name, s3_key="data/ml-1m.zip"):
    obj = s3.get_object(Bucket=bucket_name, Key=s3_key)
    zip_bytes = io.BytesIO(obj["Body"].read())
    
    with zipfile.ZipFile(zip_bytes) as z:
        with z.open("ml-1m/movies.dat") as f:
            movies = pd.read_csv(f, sep="::", engine="python",
                                 names=["MovieID", "Title", "Genres"],
                                 encoding="latin-1")
    
    movies["Year"] = movies["Title"].str.extract(r'\((\d{4})\)').astype(int)
    return movies

all_movies = load_all_movies(s3, "gomaa-hw2")
print(f"Total movies: {len(all_movies)}")

Total movies: 3883

In [ ]:
# Create embeddings for all movies not already saved to S3
all_embeddings = create_embeddings(all_movies, s3, "gomaa-hw2", s3_key="embeddings/all_embeddings.npy")
print(f"Embeddings shape: {all_embeddings.shape}")

Creating embeddings...

Loading weights: 100%|██████████| 103/103 [00:00<00:00, 7355.17it/s]
Batches: 100%|██████████| 122/122 [00:04<00:00, 24.91it/s]

Embeddings saved to s3://gomaa-hw2/embeddings/all_embeddings.npy
Embeddings shape: (3883, 384)

In [ ]:
# Recommendations for cold/top user given all the movies
colduser_results_all = recommend_movies("cold", all_movies, all_embeddings , ratings, s3, "gomaa-hw2")
topuser_results_all = recommend_movies("top", all_movies, all_embeddings , ratings, s3, "gomaa-hw2", top_user_id)

print(colduser_results_all)
print(topuser_results_all)

Saved to S3: recommendations/cold_user.json
Saved to S3: recommendations/top_user.json
{'User_Type': 'cold', 'Last_Interaction_Time': None, 'Num_Ratings': 0, 'Recommendations': ['Star Wars: Episode IV - A New Hope (1977)', 'Jurassic Park (1993)', 'Star Wars: Episode V - The Empire Strikes Back (1980)', 'Star Wars: Episode VI - Return of the Jedi (1983)', 'American Beauty (1999)']}
{'User_Type': 'top', 'Last_Interaction_Time': '2001-02-15 18:18:13', 'Num_Ratings': 649, 'Recommendations': ['Blast from the Past (1999)', 'Kids (1995)', 'Back to the Future (1985)', 'Cocoon (1985)', 'Near Dark (1987)']}

In [ ]:
# creates my (self) user profile with ratings for 10 movies, saves recommendations
def create_my_profile(movies_all, embeddings_all, s3, bucket_name):
    my_ratings = [
        {"MovieID": 215,  "Title": "Before Sunrise (1995)",            "Rating": 5},
        {"MovieID": 2572, "Title": "10 Things I Hate About You (1999)","Rating": 3},
        {"MovieID": 586,  "Title": "Home Alone (1990)",                 "Rating": 4},
        {"MovieID": 1,    "Title": "Toy Story (1995)",                  "Rating": 2},
        {"MovieID": 1721, "Title": "Titanic (1997)",                    "Rating": 5},
        {"MovieID": 2025, "Title": "Lolita (1997)",                     "Rating": 1},
        {"MovieID": 165,  "Title": "Die Hard: With a Vengeance (1995)", "Rating": 1},
        {"MovieID": 2273, "Title": "Rush Hour (1998)",                  "Rating": 1},
        {"MovieID": 1704, "Title": "Good Will Hunting (1997)",          "Rating": 5},
        {"MovieID": 1213, "Title": "GoodFellas (1990)",                 "Rating": 1},
    ]
    
    profile_df = pd.DataFrame(my_ratings)
    
    movies_reset = movies_all.reset_index(drop=True)
    liked_ids = profile_df[profile_df["Rating"] >= 4]["MovieID"]
    liked_indices = movies_reset[movies_reset["MovieID"].isin(liked_ids)].index
    
    taste_vector = embeddings_all[liked_indices].mean(axis=0, keepdims=True)
    sims = cosine_similarity(taste_vector, embeddings_all)[0]
    
    already_rated = profile_df["MovieID"].tolist()
    top_indices = [i for i in sims.argsort()[::-1] if movies_reset.iloc[i]["MovieID"] not in already_rated][:5]
    recommendations = movies_reset.iloc[top_indices][["MovieID", "Title"]]
    
    result = {
        "User_Type": "self",
        "Ratings": my_ratings,
        "Recommendations": recommendations["Title"].tolist()
    }
    
    buffer = io.BytesIO(pd.DataFrame([result]).to_json().encode())
    s3.put_object(Bucket=bucket_name, Key="recommendations/self_user.json", Body=buffer.read())
    
    return result

my_result = create_my_profile(all_movies, all_embeddings, s3, "gomaa-hw2")
print(my_result["Recommendations"])

['Déjà Vu (1997)', 'Afterglow (1997)', 'Bliss (1997)', 'Trial and Error (1997)', 'Firelight (1997)']